### ISSUE TITLE
GMP Macros Require

### ISSUE THREAD

**Issue by BeijingDiana** [wangjieest/GenericMessagePlugin#2]
Compile failed on Unreal Engine 5.1 due to lost GMPMacros.h,

**Comment by LikeScientist** [comment]
runing Build_4.27.bat error:
Running AutomationTool...
Dependencies are out of date. Compiling scripts....
  BuildCMakeLib.Automation.cs(45,54): error CS1002: 应输入 ; [F:\test\UnrealEngine-4.27.2-release\Engine\Source\Programs\AutomationTool\Scripts\AutomationScripts.Automation.csproj]
  BuildCMakeLib.Automation.cs(45,87): error CS1519: 类、结构或接口成员声明中的标记“(”无效 [F:\test\UnrealEngine-4.27.2-release\Engine\Source\Programs\AutomationTool\Scripts\AutomationScripts.Automation.csproj]
  BuildCMakeLib.Automation.cs(51,57): error CS1002: 应输入 ; [F:\test\UnrealEngine-4.27.2-release\Engine\Source\Programs\AutomationTool\Scripts\AutomationScripts.Automation.csproj]
  BuildCMakeLib.Automation.cs(51,90): error CS1519: 类、结构或接口成员声明中的标记“(”无效 [F:\test\UnrealEngine-4.27.2-release\Engine\Source\Programs\AutomationTool\Scripts\AutomationScripts.Automation.csproj]
  BuildCMakeLib.Automation.cs(71,37): error CS1002: 应输入 ; [F:\test\UnrealEngine-4.27.2-release\Engine\Source\Programs\AutomationTool\Scripts\AutomationScripts.Automation.csproj]
  BuildCMakeLib.Automation.cs(71,44): error CS1519: 类、结构或接口成员声明中的标记“;”无效 [F:\test\UnrealEngine-4.27.2-release\Engine\Source\Programs\AutomationTool\Scripts\AutomationScripts.Automation.csproj]

**Comment by LikeScientist** [comment]
The git version is rolled back to before the changes that included gmpmacro.h

The Automation.cs problem has been solved：https://forums.unrealengine.com/t/unreal-engine-version-4-27-2-i-get-an-error-when-trying-to-package-any-project/270627/10

**Comment by wangjieest** [comment]
GMPMacros.h added back
