### ISSUE TITLE
PuertsSupport.h 疑似的一处逻辑判断错误

### ISSUE THREAD

**Issue by 40kg** [wangjieest/GenericMessagePlugin#5]
![image](https://github.com/user-attachments/assets/b41bc8d2-28b7-4723-836b-d34e62c863ea)

按我的理解，图片箭头处预期的功能是，假如没有传入Times参数值，那么LeftTimes就使用默认值-1
但这里使用 == 判断会导致只有4个参数时判断成立，并造成把Leftimes赋为0

举例如下，脚本只传入有效的前4个参数
WatchedObj
MessageKey,
WeakObject,
Function
此时  （NumArgs为4 ） == GMP_Listen_Index::Times 判断成立，走进if条件，就会强制取无效值 Info[GMP_Listen_Index::Times]

**Comment by wangjieest** [comment]
fixed, lua index start from 1
